Ben new branch request
Sichere-Zuflucht/frontend pull request #11
Opened 2021-08-07 08:08 UTC by ulrichbenedikt

Hab das mal versucht, was du vorgeschlagen hast... ist das so richtig ist?

2021-08-08 08:52 UTC, fellnerse requested changes
looks good, some minor changes

2021-08-08 08:52 UTC, fellnerse commented on assets/variables.scss
> +
remove comment

2021-08-08 08:52 UTC, fellnerse commented on assets/variables.scss
> +
remove comment

2021-08-08 08:52 UTC, fellnerse commented on components/Coaching/ContactStatus.vue
> +          this.$stripe.redirectToCheckout({
does it work?

2021-08-08 08:52 UTC, fellnerse commented on components/Shared/ServiceOverview.vue
> +<script setup>
what does this mean?

2021-08-08 08:52 UTC, fellnerse commented on pages/frauen/index.vue
> +<style>
i think we should use scoped everywhere where we do not want the css applied to all other components/pages

2021-08-08 08:53 UTC, fellnerse commented on assets/variables.scss
> +
this should be the lines below
not the preview shown by github

2021-09-22 19:10 UTC, ulrichbenedikt commented on components/Shared/ServiceOverview.vue
> +<script setup>
no idea... dont know why it is there...

2021-09-22 19:31 UTC, ulrichbenedikt commented
done

2021-09-22 19:31 UTC, merged